<a href="https://colab.research.google.com/github/eshashah2901/Day1/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#creating an array using list
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [4]:
#built-in methods

In [5]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [7]:
print(np.zeros(3))

[0. 0. 0.]


In [24]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(np.ones(3))

[1. 1. 1.]


In [14]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#linspace
print(np.linspace(0,10,3))

[ 0.  5. 10.]


In [16]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
#random
#rand - in interval [0,1]
np.random.rand(2)

array([0.74723888, 0.07585974])

In [22]:
np.random.rand(3,3)

array([[0.63464671, 0.3452545 , 0.95525027],
       [0.13881418, 0.98082959, 0.82009519],
       [0.53414259, 0.37337664, 0.70502081]])

In [25]:
np.random.randn(2)

array([-0.90587175, -0.76499   ])

In [26]:
np.random.randn(2,2)

array([[ 2.72165887, -2.34272757],
       [-0.58305543, -0.96232906]])

In [27]:
np.random.randint(1,100)

64

In [28]:
np.random.randint(1,100,10)

array([17, 42, 55, 17, 41, 43, 50, 93, 54, 50])